name: latihan_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: 4.7.2
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\image\hindia.jpg
  - assets\image\mbappe.jpeg
  - assets\image\bellingham.jpg
  - assets\image\vini.jpeg
  - assets\image\vazques.jpeg
